name: Verify API URL

on:
  schedule:
    # Run every 2 days at 00:00 UTC
    - cron: "0 0 */2 * *"
  # Optional: allow manual execution
  workflow_dispatch:

# Define necessary permissions for the workflow
permissions:
  contents: write # Permission to modify repository files

jobs:
  check-api-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for proper versioning
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Verify API URL and update if needed
        run: |
          # Extract URL from .env file
          API_URL=$(grep VITE_SC_API_URL src/streaming-community/.env | cut -d '=' -f2)
          # Remove any quotes or spaces
          API_URL=$(echo $API_URL | tr -d '"' | tr -d ' ')
          echo "Checking URL: $API_URL"

          # Check if URL is valid and follow any redirects
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -I "$API_URL")

          if [[ "$HTTP_STATUS" == "301" || "$HTTP_STATUS" == "302" || "$HTTP_STATUS" == "307" || "$HTTP_STATUS" == "308" ]]; then
            # There's a redirect, get the new URL
            NEW_API_URL=$(curl -s -I "$API_URL" | grep -i "location:" | sed 's/location: //i' | tr -d '\r')
            
            # Make sure new URL has trailing slash if needed
            if [[ ! "$NEW_API_URL" =~ /$ ]]; then
              NEW_API_URL="${NEW_API_URL}/"
            fi
            
            # Update .env file
            sed -i "s|VITE_SC_API_URL=.*|VITE_SC_API_URL=$NEW_API_URL|g" src/streaming-community/.env
            
            # Configure Git
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            
            # Increment minor version
            echo "Incrementing minor version..."
            cd src/streaming-community
            npm version minor -m "Bump version to %s due to API URL change"
            cd ../..
            
            # Commit and push changes
            git add src/streaming-community/.env
            git add src/streaming-community/package.json
            git add src/streaming-community/package-lock.json
            git commit -m "Chore(sc): Update envs"
            git push
            
          elif [[ "$HTTP_STATUS" == "200" ]]; then
            echo "API URL is valid, no action needed."
          else
            echo "API URL is not reachable (HTTP status: $HTTP_STATUS), but no redirect was detected. No action taken."
          fi
